################################################################
## timer.script
## Keeps track of the time elapsed since program start.
## The value is accessible through the global variable ur_time.
################################################################
# global
ur_time = 0.0
    
# the timer thread
thread timer_thread_fn():
    while True:
        ur_time = ur_time + 0.008
        sync()
    end
end

