# this function exists only on eseries. On cb2 it needs to be defined to pass syntax checking (since it's referenced in communication.script)
def zero_ftsensor():
    return 0
end

from communication import *

################################################################
## main.script
## Starts the communication loop.
################################################################

UR_ROBOT_VERSION = UR_ROBOT_VERSION_CB2
UR_TIME_SLICE = 1./125 
start()

